# Generated by Django 3.1.7 on 2021-04-03 15:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('released_at', models.DateTimeField(null=True)),
                ('album_type', models.CharField(max_length=10, verbose_name='album or single')),
                ('cover_image', models.ImageField(upload_to='album_covers/')),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='lyrics/')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('privacy_level', models.CharField(choices=[('pub', 'public'), ('pri', 'private'), ('un', 'unlisted')], default='pub', max_length=3, verbose_name='restricts other users from viewing this playlist')),
                ('sort_by', models.CharField(choices=[('artist_name', 'Artist name'), ('album_name', 'Album name'), ('date_added', 'Date added'), ('track_name', 'Track name')], default='date', max_length=30, verbose_name='value used to sort the songs inside this playlist.')),
                ('removable', models.BooleanField(default=True)),
                ('times_played', models.PositiveIntegerField(default=0)),
                ('last_played_at', models.DateTimeField(default=user.models.aware_utc_now)),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='store the last time when a track was added or removed from this playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('country', models.CharField(blank=True, choices=[('AF', 'AFGHANISTAN'), ('AX', 'ÅLAND ISLANDS'), ('AL', 'ALBANIA'), ('DZ', 'ALGERIA'), ('AS', 'AMERICAN SAMOA'), ('AD', 'ANDORRA'), ('AO', 'ANGOLA'), ('AI', 'ANGUILLA'), ('AQ', 'ANTARCTICA'), ('AG', 'ANTIGUA AND BARBUDA'), ('AR', 'ARGENTINA'), ('AM', 'ARMENIA'), ('AW', 'ARUBA'), ('AU', 'AUSTRALIA'), ('AT', 'AUSTRIA'), ('AZ', 'AZERBAIJAN'), ('BS', 'BAHAMAS'), ('BH', 'BAHRAIN'), ('BD', 'BANGLADESH'), ('BB', 'BARBADOS'), ('BY', 'BELARUS'), ('BE', 'BELGIUM'), ('BZ', 'BELIZE'), ('BJ', 'BENIN'), ('BM', 'BERMUDA'), ('BT', 'BHUTAN'), ('BO', 'BOLIVIA, PLURINATIONAL STATE OF'), ('BQ', 'BONAIRE, SINT EUSTATIUS AND SABA'), ('BA', 'BOSNIA AND HERZEGOVINA'), ('BW', 'BOTSWANA'), ('BV', 'BOUVET ISLAND'), ('BR', 'BRAZIL'), ('IO', 'BRITISH INDIAN OCEAN TERRITORY'), ('BN', 'BRUNEI DARUSSALAM'), ('BG', 'BULGARIA'), ('BF', 'BURKINA FASO'), ('BI', 'BURUNDI'), ('KH', 'CAMBODIA'), ('CM', 'CAMEROON'), ('CA', 'CANADA'), ('CV', 'CAPE VERDE'), ('KY', 'CAYMAN ISLANDS'), ('CF', 'CENTRAL AFRICAN REPUBLIC'), ('TD', 'CHAD'), ('CL', 'CHILE'), ('CN', 'CHINA'), ('CX', 'CHRISTMAS ISLAND'), ('CC', 'COCOS (KEELING) ISLANDS'), ('CO', 'COLOMBIA'), ('KM', 'COMOROS'), ('CG', 'CONGO'), ('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE'), ('CK', 'COOK ISLANDS'), ('CR', 'COSTA RICA'), ('CI', "CÔTE D'IVOIRE"), ('HR', 'CROATIA'), ('CU', 'CUBA'), ('CW', 'CURAÇAO'), ('CY', 'CYPRUS'), ('CZ', 'CZECH REPUBLIC'), ('DK', 'DENMARK'), ('DJ', 'DJIBOUTI'), ('DM', 'DOMINICA'), ('DO', 'DOMINICAN REPUBLIC'), ('EC', 'ECUADOR'), ('EG', 'EGYPT'), ('SV', 'EL SALVADOR'), ('GQ', 'EQUATORIAL GUINEA'), ('ER', 'ERITREA'), ('EE', 'ESTONIA'), ('ET', 'ETHIOPIA'), ('FK', 'FALKLAND ISLANDS (MALVINAS)'), ('FO', 'FAROE ISLANDS'), ('FJ', 'FIJI'), ('FI', 'FINLAND'), ('FR', 'FRANCE'), ('GF', 'FRENCH GUIANA'), ('PF', 'FRENCH POLYNESIA'), ('TF', 'FRENCH SOUTHERN TERRITORIES'), ('GA', 'GABON'), ('GM', 'GAMBIA'), ('GE', 'GEORGIA'), ('DE', 'GERMANY'), ('GH', 'GHANA'), ('GI', 'GIBRALTAR'), ('GR', 'GREECE'), ('GL', 'GREENLAND'), ('GD', 'GRENADA'), ('GP', 'GUADELOUPE'), ('GU', 'GUAM'), ('GT', 'GUATEMALA'), ('GG', 'GUERNSEY'), ('GN', 'GUINEA'), ('GW', 'GUINEA-BISSAU'), ('GY', 'GUYANA'), ('HT', 'HAITI'), ('HM', 'HEARD ISLAND AND MCDONALD ISLANDS'), ('VA', 'HOLY SEE (VATICAN CITY STATE)'), ('HN', 'HONDURAS'), ('HK', 'HONG KONG'), ('HU', 'HUNGARY'), ('IS', 'ICELAND'), ('IN', 'INDIA'), ('ID', 'INDONESIA'), ('IR', 'IRAN, ISLAMIC REPUBLIC OF'), ('IQ', 'IRAQ'), ('IE', 'IRELAND'), ('IM', 'ISLE OF MAN'), ('IL', 'ISRAEL'), ('IT', 'ITALY'), ('JM', 'JAMAICA'), ('JP', 'JAPAN'), ('JE', 'JERSEY'), ('JO', 'JORDAN'), ('KZ', 'KAZAKHSTAN'), ('KE', 'KENYA'), ('KI', 'KIRIBATI'), ('KP', "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF"), ('KR', 'KOREA, REPUBLIC OF'), ('KW', 'KUWAIT'), ('KG', 'KYRGYZSTAN'), ('LA', "LAO PEOPLE'S DEMOCRATIC REPUBLIC"), ('LV', 'LATVIA'), ('LB', 'LEBANON'), ('LS', 'LESOTHO'), ('LR', 'LIBERIA'), ('LY', 'LIBYA'), ('LI', 'LIECHTENSTEIN'), ('LT', 'LITHUANIA'), ('LU', 'LUXEMBOURG'), ('MO', 'MACAO'), ('MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF'), ('MG', 'MADAGASCAR'), ('MW', 'MALAWI'), ('MY', 'MALAYSIA'), ('MV', 'MALDIVES'), ('ML', 'MALI'), ('MT', 'MALTA'), ('MH', 'MARSHALL ISLANDS'), ('MQ', 'MARTINIQUE'), ('MR', 'MAURITANIA'), ('MU', 'MAURITIUS'), ('YT', 'MAYOTTE'), ('MX', 'MEXICO'), ('FM', 'MICRONESIA, FEDERATED STATES OF'), ('MD', 'MOLDOVA, REPUBLIC OF'), ('MC', 'MONACO'), ('MN', 'MONGOLIA'), ('ME', 'MONTENEGRO'), ('MS', 'MONTSERRAT'), ('MA', 'MOROCCO'), ('MZ', 'MOZAMBIQUE'), ('MM', 'MYANMAR'), ('NA', 'NAMIBIA'), ('NR', 'NAURU'), ('NP', 'NEPAL'), ('NL', 'NETHERLANDS'), ('NC', 'NEW CALEDONIA'), ('NZ', 'NEW ZEALAND'), ('NI', 'NICARAGUA'), ('NE', 'NIGER'), ('NG', 'NIGERIA'), ('NU', 'NIUE'), ('NF', 'NORFOLK ISLAND'), ('MP', 'NORTHERN MARIANA ISLANDS'), ('NO', 'NORWAY'), ('OM', 'OMAN'), ('PK', 'PAKISTAN'), ('PW', 'PALAU'), ('PS', 'PALESTINE, STATE OF'), ('PA', 'PANAMA'), ('PG', 'PAPUA NEW GUINEA'), ('PY', 'PARAGUAY'), ('PE', 'PERU'), ('PH', 'PHILIPPINES'), ('PN', 'PITCAIRN'), ('PL', 'POLAND'), ('PT', 'PORTUGAL'), ('PR', 'PUERTO RICO'), ('QA', 'QATAR'), ('RE', 'RÉUNION'), ('RO', 'ROMANIA'), ('RU', 'RUSSIAN FEDERATION'), ('RW', 'RWANDA'), ('BL', 'SAINT BARTHÉLEMY'), ('SH', 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA'), ('KN', 'SAINT KITTS AND NEVIS'), ('LC', 'SAINT LUCIA'), ('MF', 'SAINT MARTIN (FRENCH PART)'), ('PM', 'SAINT PIERRE AND MIQUELON'), ('VC', 'SAINT VINCENT AND THE GRENADINES'), ('WS', 'SAMOA'), ('SM', 'SAN MARINO'), ('ST', 'SAO TOME AND PRINCIPE'), ('SA', 'SAUDI ARABIA'), ('SN', 'SENEGAL'), ('RS', 'SERBIA'), ('SC', 'SEYCHELLES'), ('SL', 'SIERRA LEONE'), ('SG', 'SINGAPORE'), ('SX', 'SINT MAARTEN (DUTCH PART)'), ('SK', 'SLOVAKIA'), ('SI', 'SLOVENIA'), ('SB', 'SOLOMON ISLANDS'), ('SO', 'SOMALIA'), ('ZA', 'SOUTH AFRICA'), ('GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS'), ('SS', 'SOUTH SUDAN'), ('ES', 'SPAIN'), ('LK', 'SRI LANKA'), ('SD', 'SUDAN'), ('SR', 'SURINAME'), ('SJ', 'SVALBARD AND JAN MAYEN'), ('SZ', 'SWAZILAND'), ('SE', 'SWEDEN'), ('CH', 'SWITZERLAND'), ('SY', 'SYRIAN ARAB REPUBLIC'), ('TW', 'TAIWAN, PROVINCE OF CHINA'), ('TJ', 'TAJIKISTAN'), ('TZ', 'TANZANIA, UNITED REPUBLIC OF'), ('TH', 'THAILAND'), ('TL', 'TIMOR-LESTE'), ('TG', 'TOGO'), ('TK', 'TOKELAU'), ('TO', 'TONGA'), ('TT', 'TRINIDAD AND TOBAGO'), ('TN', 'TUNISIA'), ('TR', 'TURKEY'), ('TM', 'TURKMENISTAN'), ('TC', 'TURKS AND CAICOS ISLANDS'), ('TV', 'TUVALU'), ('UG', 'UGANDA'), ('UA', 'UKRAINE'), ('AE', 'UNITED ARAB EMIRATES'), ('GB', 'UNITED KINGDOM'), ('US', 'UNITED STATES'), ('UM', 'UNITED STATES MINOR OUTLYING ISLANDS'), ('UY', 'URUGUAY'), ('UZ', 'UZBEKISTAN'), ('VU', 'VANUATU'), ('VE', 'VENEZUELA, BOLIVARIAN REPUBLIC OF'), ('VN', 'VIET NAM'), ('VG', 'VIRGIN ISLANDS, BRITISH'), ('VI', 'VIRGIN ISLANDS, U.S.'), ('WF', 'WALLIS AND FUTUNA'), ('EH', 'WESTERN SAHARA'), ('YE', 'YEMEN'), ('ZM', 'ZAMBIA'), ('ZW', 'ZIMBABWE')], default='US', max_length=50)),
                ('profile_pic', models.ImageField(blank=True, default='', upload_to='userbase/')),
                ('gender', models.CharField(blank=True, choices=[('', 'Choose..'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=20)),
                ('age', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(150)])),
                ('created_at', models.DateTimeField(default=user.models.aware_utc_now, verbose_name='date when the account was created')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('rock', 'Rock'), ('hip hop', 'Hip hop music'), ('jazz', 'Jazz'), ('folk', 'Folk music'), ('pop', 'Pop music'), ('blues', 'Blues'), ('heavy metal', 'Heavy metal'), ('country', 'Country music'), ('classical', 'Classical music'), ('punk rock', 'Punk rock'), ('reggae', 'Reggae'), ('electronic', 'Electronic music'), ('techno', 'Techno'), ('funk', 'Funk'), ('alternative rock', 'Alternative rock'), ('indie rock', 'Indie rock'), ('hardcore', 'Hardcore'), ('ambient', 'Ambient music'), ('hardcore punk', 'Hardcore punk'), ('instrumental', 'Instrumental'), ('orchestra', 'Orchestra'), ('dubstep', 'Dubstep'), ('grunge', 'Grunge'), ('opera', 'Opera'), ('western', 'Western music'), ('progressive rock', 'Progressive rock'), ('other', 'Other')], default='other', max_length=50)),
                ('released_at', models.DateTimeField(null=True)),
                ('duration', models.PositiveIntegerField(verbose_name='duration of track in secs')),
                ('explicit', models.BooleanField()),
                ('created_at', models.DateTimeField(default=user.models.aware_utc_now, verbose_name='date when the track was uploaded')),
                ('total_streams', models.PositiveIntegerField()),
                ('cover_image', models.ImageField(upload_to='track_covers/')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.album')),
            ],
        ),
        migrations.CreateModel(
            name='Adminbase',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.profile')),
                ('level', models.CharField(max_length=1)),
            ],
            bases=('user.profile',),
        ),
        migrations.CreateModel(
            name='Userbase',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.profile')),
                ('plan_type', models.CharField(default='free', max_length=10)),
            ],
            bases=('user.profile',),
        ),
        migrations.CreateModel(
            name='TrackPlaylists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=user.models.aware_utc_now)),
                ('playlists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.track')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(through='user.TrackPlaylists', to='user.Track'),
        ),
        migrations.CreateModel(
            name='FavouritesTracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=user.models.aware_utc_now)),
                ('tracks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.track')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('userbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.userbase')),
                ('social_links', models.CharField(blank=True, default='', max_length=100)),
            ],
            bases=('user.userbase',),
        ),
        migrations.CreateModel(
            name='UserbasePlaylists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write', models.BooleanField(verbose_name='whether user can edit playlists or not')),
                ('playlists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.playlist')),
                ('userbase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userbase')),
            ],
        ),
        migrations.AddField(
            model_name='userbase',
            name='favourites',
            field=models.ManyToManyField(through='user.FavouritesTracks', to='user.Track'),
        ),
        migrations.AddField(
            model_name='userbase',
            name='followers',
            field=models.ManyToManyField(through='user.Followers', to='user.Userbase'),
        ),
        migrations.AddField(
            model_name='userbase',
            name='playlists',
            field=models.ManyToManyField(through='user.UserbasePlaylists', to='user.Playlist'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='owner',
            field=models.ManyToManyField(to='user.Userbase'),
        ),
        migrations.AddField(
            model_name='followers',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_follower', to='user.userbase'),
        ),
        migrations.AddField(
            model_name='followers',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_leader', to='user.userbase'),
        ),
        migrations.AddField(
            model_name='favouritestracks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userbase'),
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ManyToManyField(to='user.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(to='user.Artist'),
        ),
    ]
