# Generated by Django 3.1.7 on 2021-04-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
