# Generated by Django 3.1.7 on 2021-04-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lyrics',
        ),
        migrations.AddField(
            model_name='track',
            name='location',
            field=models.FileField(default='', upload_to='track_audio/'),
            preserve_default=False,
        ),
    ]
