# Generated by Django 3.1.7 on 2021-04-17 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210417_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackplaylists',
            old_name='track',
            new_name='tracks',
        ),
    ]
