# Generated by Django 3.1.7 on 2021-04-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210418_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='adminbase',
            options={'verbose_name': 'Adminbase', 'verbose_name_plural': 'Adminbase'},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Artist', 'verbose_name_plural': 'Artists'},
        ),
        migrations.AlterModelOptions(
            name='favouritestracks',
            options={'verbose_name': 'FavouritesTrack', 'verbose_name_plural': 'FavouritesTracks'},
        ),
        migrations.AlterModelOptions(
            name='followers',
            options={'verbose_name': 'Follower', 'verbose_name_plural': 'Follower'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='trackplaylists',
            options={'verbose_name': 'TrackPlaylist', 'verbose_name_plural': 'TrackPlaylists'},
        ),
        migrations.AlterModelOptions(
            name='userbase',
            options={'verbose_name': 'Userbase', 'verbose_name_plural': 'Userbase'},
        ),
        migrations.AlterModelOptions(
            name='userbaseplaylists',
            options={'verbose_name': 'UserbasePlaylist', 'verbose_name_plural': 'UserbasePlaylists'},
        ),
        migrations.AddField(
            model_name='playlist',
            name='cover_image',
            field=models.ImageField(default='', upload_to='playlist_covers/'),
            preserve_default=False,
        ),
    ]
